FROM --platform=linux/amd64 python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pyinstaller

COPY . .

VOLUME ["/app/dist"]

CMD ["pyinstaller", "--onefile", "--distpath", "/app/dist", "--name", "RealtimeReplicator_mac", "main.py"]
