FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc python3-dev binutils

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pyinstaller

COPY . .

VOLUME ["/app/dist"]

CMD ["pyinstaller", "--onefile", "--distpath", "/app/dist", "--name", "RealtimeReplicator_linux", "main.py"]