FROM amazonlinux:2023

WORKDIR /app

RUN yum update -y && yum install -y python3 python3-pip python3-devel gcc binutils

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install pyinstaller

COPY . .

VOLUME ["/app/dist"]

CMD ["pyinstaller", "--onefile", "--distpath", "/app/dist", "--name", "RealtimeReplicator_al2023", "main.py"]